name: day_selector
description: Flutter widget to select week day easily, week day or workable day mode are available, same as unique, multiple selection
version: 1.0.0
author: jaumard <jimmy.aumard@gmail.com>
homepage: https://github.com/jaumard/day_selector.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
